{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SOSTECH&CODE</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home_page/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Python, simple y sencillo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Información</a></li>
                        <li class="nav-item"><a class="nav-link" href="/about/">Sobre Nosotros</a></li>
                        {% if user.is_authenticated %}
                            <!--<li class="nav-item"><a class="nav-link" href="#!">Menú</a></li>-->
                            <li class="nav-item"><a class="nav-link" href="/accounts/profile/">Perfil</a></li>
                            <li class="nav-item"><a class="nav-link" href="/logout/">Cerrar Sesión</a></li>
                            <div class="dropdown">
                                <button class="menu-button">Menú</button>
                                <div class="dropdown-content">
                                    <a href="/classes/">Clases</a>
                                    <a href="/forum/">Foro</a>
                                    <a href="/direct/">Mensajes</a>
                                </div>
                            </div>
                            </div>    
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="/login/">Iniciar Sesión</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://cutewallpaper.org/21/programming-wallpapers-hd/37-Programmer-Code-Wallpaper-Backgrounds-Free-Download.png')">
            <div class="text-center my-5">
                <img class="img-fluid rounded-circle mb-4" src="https://i.imgur.com/Bb059XS.jpg" alt="..." />
                <!--<h1 class="text-white fs-3 fw-bolder">Python, CSS, HTML</h1>-->
                <!--<p class="text-white">Con nuestros cursos puedes aprender Python de forma sencilla.</p>-->
            </div>
        </header>
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <span id="tut-errors"></span><h1><span class="section-number">8. </span>Errores y excepciones<a class="headerlink" href="#errors-and-exceptions" title="Enlazar permanentemente con este título">¶</a></h1>
                        <p>Hasta ahora los mensajes de error apenas habían sido mencionados, pero si has probado los ejemplos anteriores probablemente hayas visto algunos.  Hay (al menos) dos tipos diferentes de errores: <em>errores de sintaxis</em> y <em>excepciones</em>.</p>
                        <div class="section" id="syntax-errors">
                        <span id="tut-syntaxerrors"></span><h2><span class="section-number">8.1. </span>Errores de sintaxis<a class="headerlink" href="#syntax-errors" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>Los errores de sintaxis, también conocidos como errores de interpretación, son quizás el tipo de queja más común que tenés cuando todavía estás aprendiendo Python:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">while</span> <span class="kc">True</span> <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Hello world&#39;</span><span class="p">)</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>
                            <span class="k">while</span> <span class="kc">True</span> <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Hello world&#39;</span><span class="p">)</span>
                                           <span class="o">^</span>
                        <span class="gr">SyntaxError</span>: <span class="n">invalid syntax</span>
                        </pre></div>
                        </div>
                        <p>El intérprete reproduce la línea responsable del error y muestra una pequeña “flecha” que apunta al primer lugar donde se detectó el error.  El error ha sido provocado (o al menos detectado) en el elemento que <em>precede</em> a la flecha: en el ejemplo, el error se detecta en la función <a class="reference internal" href="../library/functions.html#print" title="print"><code class="xref py py-func docutils literal notranslate"><span class="pre">print()</span></code></a>, ya que faltan dos puntos (<code class="docutils literal notranslate"><span class="pre">':'</span></code>) antes del mismo.  Se muestran el nombre del archivo y el número de línea para que sepas dónde mirar en caso de que la entrada venga de un programa.</p>
                        </div>
                        <div class="section" id="exceptions">
                        <span id="tut-exceptions"></span><h2><span class="section-number">8.2. </span>Excepciones<a class="headerlink" href="#exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>Incluso si una declaración o expresión es sintácticamente correcta, puede generar un error cuando se intenta ejecutar.  Los errores detectados durante la ejecución se llaman <em>excepciones</em>, y no son incondicionalmente fatales: pronto aprenderás a gestionarlos en programas Python.  Sin embargo, la mayoría de las excepciones no son gestionadas por el código, y resultan en mensajes de error como los mostrados aquí:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="mi">10</span> <span class="o">*</span> <span class="p">(</span><span class="mi">1</span><span class="o">/</span><span class="mi">0</span><span class="p">)</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="mi">4</span> <span class="o">+</span> <span class="n">spam</span><span class="o">*</span><span class="mi">3</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">NameError</span>: <span class="n">name &#39;spam&#39; is not defined</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="s1">&#39;2&#39;</span> <span class="o">+</span> <span class="mi">2</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">TypeError</span>: <span class="n">can only concatenate str (not &quot;int&quot;) to str</span>
                        </pre></div>
                        </div>
                        <p>La última línea de los mensajes de error indica qué ha sucedido.  Hay excepciones de diferentes tipos, y el tipo se imprime como parte del mensaje: los tipos en el ejemplo son: <a class="reference internal" href="../library/exceptions.html#ZeroDivisionError" title="ZeroDivisionError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code></a>, <a class="reference internal" href="../library/exceptions.html#NameError" title="NameError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">NameError</span></code></a> y <a class="reference internal" href="../library/exceptions.html#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a>.  La cadena mostrada como tipo de la excepción es el nombre de la excepción predefinida que ha ocurrido.  Esto es válido para todas las excepciones predefinidas del intérprete, pero no tiene por que ser así para excepciones definidas por el usuario (aunque es una convención útil).  Los nombres de las excepciones estándar son identificadores incorporados al intérprete (no son palabras clave reservadas).</p>
                        <p>El resto de la línea provee información basado en el tipo de la excepción y qué la causó.</p>
                        <p>La parte anterior del mensaje de error muestra el contexto donde ocurrió la excepción, en forma de seguimiento de pila. En general, contiene un seguimiento de pila que enumera las líneas de origen; sin embargo, no mostrará las líneas leídas desde la entrada estándar.</p>
                        <p><a class="reference internal" href="../library/exceptions.html#bltin-exceptions"><span class="std std-ref">Excepciones incorporadas</span></a> lista las excepciones predefinidas y sus significados.</p>
                        </div>
                        <div class="section" id="handling-exceptions">
                        <span id="tut-handling"></span><h2><span class="section-number">8.3. </span>Gestionando excepciones<a class="headerlink" href="#handling-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>Es posible escribir programas que gestionen determinadas excepciones.  Véase el siguiente ejemplo, que le pide al usuario una entrada hasta que ingrese un entero válido, pero permite al usuario interrumpir el programa (usando <kbd class="kbd docutils literal notranslate"><kbd class="kbd docutils literal notranslate">Control</kbd>-<kbd class="kbd docutils literal notranslate">C</kbd></kbd> o lo que soporte el sistema operativo); nótese que una interrupción generada por el usuario es señalizada generando la excepción <a class="reference internal" href="../library/exceptions.html#KeyboardInterrupt" title="KeyboardInterrupt"><code class="xref py py-exc docutils literal notranslate"><span class="pre">KeyboardInterrupt</span></code></a>.</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&quot;Please enter a number: &quot;</span><span class="p">))</span>
                        <span class="gp">... </span>        <span class="k">break</span>
                        <span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Oops!  That was no valid number.  Try again...&quot;</span><span class="p">)</span>
                        <span class="gp">...</span>
                        </pre></div>
                        </div>
                        <p>La sentencia <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> funciona de la siguiente manera.</p>
                        <ul class="simple">
                        <li><p>Primero, se ejecuta la cláusula <em>try</em> (la(s) linea(s) entre las palabras reservadas <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> y la <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a>).</p></li>
                        <li><p>Si no ocurre ninguna excepción, la cláusula <em>except</em> se omite y la ejecución de la cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> finaliza.</p></li>
                        <li><p>Si ocurre una excepción durante la ejecución de la cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a>, se omite el resto de la cláusula. Luego, si su tipo coincide con la excepción nombrada después de la palabra clave <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a>, se ejecuta la <em>cláusula except</em>, y luego la ejecución continúa después del bloque try/except.</p></li>
                        <li><p>Si ocurre una excepción que no coincide con la indicada en la <em>cláusula except</em> se pasa a los <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> más externos; si no se encuentra un gestor, se genera una <em>unhandled exception</em> (excepción no gestionada) y la ejecución se interrumpe con un mensaje como el que se muestra arriba.</p></li>
                        </ul>
                        <p>Una declaración <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> puede tener más de una <em>cláusula except</em>, para especificar gestores para diferentes excepciones. Como máximo, se ejecutará un gestor. Los gestores solo manejan las excepciones que ocurren en la <em>cláusula try</em> correspondiente, no en otros gestores de la misma declaración <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code>. Una <em>cláusula except</em> puede nombrar múltiples excepciones como una tupla entre paréntesis, por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="o">...</span> <span class="k">except</span> <span class="p">(</span><span class="ne">RuntimeError</span><span class="p">,</span> <span class="ne">TypeError</span><span class="p">,</span> <span class="ne">NameError</span><span class="p">):</span>
                        <span class="o">...</span>     <span class="k">pass</span>
                        </pre></div>
                        </div>
                        <p>Una clase en una cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> es compatible con una excepción si es de la misma clase o de una clase derivada de la misma (pero no de la otra manera — una <em>cláusula except</em> listando una clase derivada no es compatible con una clase base). Por ejemplo, el siguiente código imprimirá B, C y D, en ese orden:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">B</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
                            <span class="k">pass</span>
                        
                        <span class="k">class</span> <span class="nc">C</span><span class="p">(</span><span class="n">B</span><span class="p">):</span>
                            <span class="k">pass</span>
                        
                        <span class="k">class</span> <span class="nc">D</span><span class="p">(</span><span class="n">C</span><span class="p">):</span>
                            <span class="k">pass</span>
                        
                        <span class="k">for</span> <span class="bp">cls</span> <span class="ow">in</span> <span class="p">[</span><span class="n">B</span><span class="p">,</span> <span class="n">C</span><span class="p">,</span> <span class="n">D</span><span class="p">]:</span>
                            <span class="k">try</span><span class="p">:</span>
                                <span class="k">raise</span> <span class="bp">cls</span><span class="p">()</span>
                            <span class="k">except</span> <span class="n">D</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;D&quot;</span><span class="p">)</span>
                            <span class="k">except</span> <span class="n">C</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;C&quot;</span><span class="p">)</span>
                            <span class="k">except</span> <span class="n">B</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;B&quot;</span><span class="p">)</span>
                        </pre></div>
                        </div>
                        <p>Nótese que si las <em>cláusulas except</em> estuvieran invertidas (con <code class="docutils literal notranslate"><span class="pre">except</span> <span class="pre">B</span></code> primero), habría impreso B, B, B — se usa la primera <em>cláusula except</em> coincidente.</p>
                        <p>Todas las excepciones heredan de <a class="reference internal" href="../library/exceptions.html#BaseException" title="BaseException"><code class="xref py py-exc docutils literal notranslate"><span class="pre">BaseException</span></code></a>, por lo que se puede utilizar como comodín. ¡Use esto con extrema precaución, ya que es fácil enmascarar un error de programación real de esta manera! También se puede usar para imprimir un mensaje de error y luego volver a generar la excepción (permitiendo que la función que llama también maneje la excepción):</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">sys</span>
                        
                        <span class="k">try</span><span class="p">:</span>
                            <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s1">&#39;myfile.txt&#39;</span><span class="p">)</span>
                            <span class="n">s</span> <span class="o">=</span> <span class="n">f</span><span class="o">.</span><span class="n">readline</span><span class="p">()</span>
                            <span class="n">i</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">strip</span><span class="p">())</span>
                        <span class="k">except</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
                            <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;OS error: </span><span class="si">{0}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">err</span><span class="p">))</span>
                        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
                            <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Could not convert data to an integer.&quot;</span><span class="p">)</span>
                        <span class="k">except</span> <span class="ne">BaseException</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
                            <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;Unexpected </span><span class="si">{</span><span class="n">err</span><span class="si">=}</span><span class="s2">, </span><span class="si">{</span><span class="nb">type</span><span class="p">(</span><span class="n">err</span><span class="p">)</span><span class="si">=}</span><span class="s2">&quot;</span><span class="p">)</span>
                            <span class="k">raise</span>
                        </pre></div>
                        </div>
                        <p>Alternativamente, la última cláusula except puede omitir el(los) nombre(s) de excepción, sin embargo, el valor de la excepción debe recuperarse de <code class="docutils literal notranslate"><span class="pre">sys.exc_info()[1]</span></code>.</p>
                        <p>La declaración <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> … <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> tiene una <em>cláusula else</em> opcional, que, cuando está presente, debe seguir todas las <em>cláusulas except</em>. Es útil para el código que debe ejecutarse si la <em>cláusula try</em> no lanza una excepción. Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">for</span> <span class="n">arg</span> <span class="ow">in</span> <span class="n">sys</span><span class="o">.</span><span class="n">argv</span><span class="p">[</span><span class="mi">1</span><span class="p">:]:</span>
                            <span class="k">try</span><span class="p">:</span>
                                <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="n">arg</span><span class="p">,</span> <span class="s1">&#39;r&#39;</span><span class="p">)</span>
                            <span class="k">except</span> <span class="ne">OSError</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;cannot open&#39;</span><span class="p">,</span> <span class="n">arg</span><span class="p">)</span>
                            <span class="k">else</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="n">arg</span><span class="p">,</span> <span class="s1">&#39;has&#39;</span><span class="p">,</span> <span class="nb">len</span><span class="p">(</span><span class="n">f</span><span class="o">.</span><span class="n">readlines</span><span class="p">()),</span> <span class="s1">&#39;lines&#39;</span><span class="p">)</span>
                                <span class="n">f</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
                        </pre></div>
                        </div>
                        <p>El uso de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">else</span></code> es mejor que agregar código adicional en la cláusula <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> porque evita capturar accidentalmente una excepción que no fue generada por el código que está protegido por la declaración <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code> … <code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code>.</p>
                        <p>Cuando ocurre una excepción, puede tener un valor asociado, también conocido como el <em>argumento</em> de la excepción.  La presencia y el tipo de argumento depende del tipo de excepción.</p>
                        <p>La <em>cláusula except</em> puede especificar una variable después del nombre de la excepción. La variable está vinculada a una instancia de excepción con los argumentos almacenados en <code class="docutils literal notranslate"><span class="pre">instance.args</span></code>. Por conveniencia, la instancia de excepción define <code class="xref py py-meth docutils literal notranslate"><span class="pre">__str__()</span></code> para que los argumentos se puedan imprimir directamente sin tener que hacer referencia a <code class="docutils literal notranslate"><span class="pre">.args</span></code>. También se puede crear una instancia de una excepción antes de generarla y agregarle los atributos que desee.</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s1">&#39;spam&#39;</span><span class="p">,</span> <span class="s1">&#39;eggs&#39;</span><span class="p">)</span>
                        <span class="gp">... </span><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">inst</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="nb">type</span><span class="p">(</span><span class="n">inst</span><span class="p">))</span>    <span class="c1"># the exception instance</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="n">inst</span><span class="o">.</span><span class="n">args</span><span class="p">)</span>     <span class="c1"># arguments stored in .args</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="n">inst</span><span class="p">)</span>          <span class="c1"># __str__ allows args to be printed directly,</span>
                        <span class="gp">... </span>                         <span class="c1"># but may be overridden in exception subclasses</span>
                        <span class="gp">... </span>    <span class="n">x</span><span class="p">,</span> <span class="n">y</span> <span class="o">=</span> <span class="n">inst</span><span class="o">.</span><span class="n">args</span>     <span class="c1"># unpack args</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;x =&#39;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;y =&#39;</span><span class="p">,</span> <span class="n">y</span><span class="p">)</span>
                        <span class="gp">...</span>
                        <span class="go">&lt;class &#39;Exception&#39;&gt;</span>
                        <span class="go">(&#39;spam&#39;, &#39;eggs&#39;)</span>
                        <span class="go">(&#39;spam&#39;, &#39;eggs&#39;)</span>
                        <span class="go">x = spam</span>
                        <span class="go">y = eggs</span>
                        </pre></div>
                        </div>
                        <p>Si una excepción tiene argumentos, estos se imprimen como en la parte final (el “detalle”) del mensaje para las excepciones no gestionadas (“<em>Unhandled exception</em>”).</p>
                        <p>Los gestores de excepciones no solo gestionan las excepciones si ocurren inmediatamente en la <em>cláusula try</em>, sino también si ocurren dentro de funciones que son llamadas (incluso indirectamente) en la <em>cláusula try</em>. Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">this_fails</span><span class="p">():</span>
                        <span class="gp">... </span>    <span class="n">x</span> <span class="o">=</span> <span class="mi">1</span><span class="o">/</span><span class="mi">0</span>
                        <span class="gp">...</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="n">this_fails</span><span class="p">()</span>
                        <span class="gp">... </span><span class="k">except</span> <span class="ne">ZeroDivisionError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Handling run-time error:&#39;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
                        <span class="gp">...</span>
                        <span class="go">Handling run-time error: division by zero</span>
                        </pre></div>
                        </div>
                        </div>
                        <div class="section" id="raising-exceptions">
                        <span id="tut-raising"></span><h2><span class="section-number">8.4. </span>Lanzando excepciones<a class="headerlink" href="#raising-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>La declaración <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a> permite al programador forzar a que ocurra una excepción específica.  Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">raise</span> <span class="ne">NameError</span><span class="p">(</span><span class="s1">&#39;HiThere&#39;</span><span class="p">)</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">NameError</span>: <span class="n">HiThere</span>
                        </pre></div>
                        </div>
                        <p>El único argumento de <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a> indica la excepción a generarse. Tiene que ser o una instancia de excepción, o una clase de excepción (una clase que hereda de <a class="reference internal" href="../library/exceptions.html#Exception" title="Exception"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a>). Si se pasa una clase de excepción, la misma será instanciada implícitamente llamando a su constructor sin argumentos:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">raise</span> <span class="ne">ValueError</span>  <span class="c1"># shorthand for &#39;raise ValueError()&#39;</span>
                        </pre></div>
                        </div>
                        <p>Si es necesario determinar si una excepción fue lanzada pero sin intención de gestionarla, una versión simplificada de la instrucción <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a> te permite relanzarla:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">NameError</span><span class="p">(</span><span class="s1">&#39;HiThere&#39;</span><span class="p">)</span>
                        <span class="gp">... </span><span class="k">except</span> <span class="ne">NameError</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;An exception flew by!&#39;</span><span class="p">)</span>
                        <span class="gp">... </span>    <span class="k">raise</span>
                        <span class="gp">...</span>
                        <span class="go">An exception flew by!</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">NameError</span>: <span class="n">HiThere</span>
                        </pre></div>
                        </div>
                        </div>
                        <div class="section" id="exception-chaining">
                        <span id="tut-exception-chaining"></span><h2><span class="section-number">8.5. </span>Encadenamiento de excepciones<a class="headerlink" href="#exception-chaining" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>La declaración <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">raise</span></code></a> permite una palabra clave opcional <a class="reference internal" href="../reference/simple_stmts.html#raise"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">from</span></code></a> que habilita el encadenamiento de excepciones. Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="c1"># exc must be exception instance or None.</span>
                        <span class="k">raise</span> <span class="ne">RuntimeError</span> <span class="kn">from</span> <span class="nn">exc</span>
                        </pre></div>
                        </div>
                        <p>Esto puede resultar útil cuando está transformando excepciones. Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">func</span><span class="p">():</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">ConnectionError</span>
                        <span class="gp">...</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="n">func</span><span class="p">()</span>
                        <span class="gp">... </span><span class="k">except</span> <span class="ne">ConnectionError</span> <span class="k">as</span> <span class="n">exc</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">&#39;Failed to open database&#39;</span><span class="p">)</span> <span class="kn">from</span> <span class="nn">exc</span>
                        <span class="gp">...</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">func</span>
                        <span class="gr">ConnectionError</span>
                        
                        <span class="go">The above exception was the direct cause of the following exception:</span>
                        
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">4</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">RuntimeError</span>: <span class="n">Failed to open database</span>
                        </pre></div>
                        </div>
                        <p>El encadenamiento de excepciones ocurre automáticamente cuando se lanza una excepción dentro de una sección <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> o <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a>. Esto se puede desactivar usando el modismo <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">None</span></code>:</p>
                        <div class="doctest highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="nb">open</span><span class="p">(</span><span class="s1">&#39;database.sqlite&#39;</span><span class="p">)</span>
                        <span class="gp">... </span><span class="k">except</span> <span class="ne">OSError</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">RuntimeError</span> <span class="kn">from</span> <span class="bp">None</span>
                        <span class="gp">...</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">4</span>, in <span class="n">&lt;module&gt;</span>
                        <span class="gr">RuntimeError</span>
                        </pre></div>
                        </div>
                        <p>Para obtener más información sobre la mecánica del encadenamiento, consulte <a class="reference internal" href="../library/exceptions.html#bltin-exceptions"><span class="std std-ref">Excepciones incorporadas</span></a>.</p>
                        </div>
                        <div class="section" id="user-defined-exceptions">
                        <span id="tut-userexceptions"></span><h2><span class="section-number">8.6. </span>Excepciones definidas por el usuario<a class="headerlink" href="#user-defined-exceptions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>Los programas pueden nombrar sus propias excepciones creando una nueva clase excepción (mirá <a class="reference internal" href="classes.html#tut-classes"><span class="std std-ref">Clases</span></a> para más información sobre las clases de Python).  Las excepciones, típicamente, deberán derivar de la clase <a class="reference internal" href="../library/exceptions.html#Exception" title="Exception"><code class="xref py py-exc docutils literal notranslate"><span class="pre">Exception</span></code></a>, directa o indirectamente.</p>
                        <p>Exception classes can be defined which do anything any other class can do, but
                        are usually kept simple, often only offering a number of attributes that allow
                        information about the error to be extracted by handlers for the exception.</p>
                        <p>La mayoría de las excepciones se definen con nombres acabados en «Error», de manera similar a la nomenclatura de las excepciones estándar.</p>
                        <p>Muchos módulos estándar definen sus propias excepciones para reportar errores que pueden ocurrir en funciones propias. Se puede encontrar más información sobre clases en el capítulo <a class="reference internal" href="classes.html#tut-classes"><span class="std std-ref">Clases</span></a>.</p>
                        </div>
                        <div class="section" id="defining-clean-up-actions">
                        <span id="tut-cleanup"></span><h2><span class="section-number">8.7. </span>Definiendo acciones de limpieza<a class="headerlink" href="#defining-clean-up-actions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>La declaración <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> tiene otra cláusula opcional cuyo propósito es definir acciones de limpieza que serán ejecutadas bajo ciertas circunstancias. Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="k">raise</span> <span class="ne">KeyboardInterrupt</span>
                        <span class="gp">... </span><span class="k">finally</span><span class="p">:</span>
                        <span class="gp">... </span>    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Goodbye, world!&#39;</span><span class="p">)</span>
                        <span class="gp">...</span>
                        <span class="go">Goodbye, world!</span>
                        <span class="nc">KeyboardInterrupt</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
                        </pre></div>
                        </div>
                        <p>Si una cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> está presente, el bloque <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> se ejecutará al final antes de que todo el bloque <a class="reference internal" href="../reference/compound_stmts.html#try"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code></a> se complete. La cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> se ejecuta independientemente de que la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code> produzca o no una excepción. Los siguientes puntos explican casos más complejos en los que se produce una excepción:</p>
                        <ul class="simple">
                        <li><p>Si ocurre una excepción durante la ejecución de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code>, la excepción podría ser gestionada por una cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a>. Si la excepción no es gestionada por una cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code>, la excepción es relanzada después de que se ejecute el bloque de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code>.</p></li>
                        <li><p>Podría aparecer una excepción durante la ejecución de una cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code> o <code class="xref std std-keyword docutils literal notranslate"><span class="pre">else</span></code>. De nuevo, la excepción será relanzada después de que el bloque de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> se ejecute.</p></li>
                        <li><p>Si la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> ejecuta una declaración <a class="reference internal" href="../reference/simple_stmts.html#break"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">break</span></code></a>, <a class="reference internal" href="../reference/simple_stmts.html#continue"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">continue</span></code></a> o <a class="reference internal" href="../reference/simple_stmts.html#return"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">return</span></code></a>, las excepciones no se vuelven a lanzar.</p></li>
                        <li><p>Si el bloque <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code> llega a una sentencia <a class="reference internal" href="../reference/simple_stmts.html#break"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">break</span></code></a>, <a class="reference internal" href="../reference/simple_stmts.html#continue"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">continue</span></code></a> o <a class="reference internal" href="../reference/simple_stmts.html#return"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">return</span></code></a>, la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> se ejecutará justo antes de la ejecución de dicha sentencia.</p></li>
                        <li><p>Si una cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code> incluye una sentencia <code class="xref std std-keyword docutils literal notranslate"><span class="pre">return</span></code>, el valor retornado será el de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code>, no la del de la sentencia <code class="xref std std-keyword docutils literal notranslate"><span class="pre">return</span></code> de la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">try</span></code>.</p></li>
                        </ul>
                        <p>Por ejemplo:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">bool_return</span><span class="p">():</span>
                        <span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="k">return</span> <span class="kc">True</span>
                        <span class="gp">... </span>    <span class="k">finally</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="k">return</span> <span class="kc">False</span>
                        <span class="gp">...</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="n">bool_return</span><span class="p">()</span>
                        <span class="go">False</span>
                        </pre></div>
                        </div>
                        <p>Un ejemplo más complicado:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">divide</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
                        <span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="n">result</span> <span class="o">=</span> <span class="n">x</span> <span class="o">/</span> <span class="n">y</span>
                        <span class="gp">... </span>    <span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;division by zero!&quot;</span><span class="p">)</span>
                        <span class="gp">... </span>    <span class="k">else</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;result is&quot;</span><span class="p">,</span> <span class="n">result</span><span class="p">)</span>
                        <span class="gp">... </span>    <span class="k">finally</span><span class="p">:</span>
                        <span class="gp">... </span>        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;executing finally clause&quot;</span><span class="p">)</span>
                        <span class="gp">...</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">1</span><span class="p">)</span>
                        <span class="go">result is 2.0</span>
                        <span class="go">executing finally clause</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
                        <span class="go">division by zero!</span>
                        <span class="go">executing finally clause</span>
                        <span class="gp">&gt;&gt;&gt; </span><span class="n">divide</span><span class="p">(</span><span class="s2">&quot;2&quot;</span><span class="p">,</span> <span class="s2">&quot;1&quot;</span><span class="p">)</span>
                        <span class="go">executing finally clause</span>
                        <span class="gt">Traceback (most recent call last):</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
                          File <span class="nb">&quot;&lt;stdin&gt;&quot;</span>, line <span class="m">3</span>, in <span class="n">divide</span>
                        <span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for /: &#39;str&#39; and &#39;str&#39;</span>
                        </pre></div>
                        </div>
                        <p>Como se puede ver, la cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> siempre se ejecuta.  La excepción <a class="reference internal" href="../library/exceptions.html#TypeError" title="TypeError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">TypeError</span></code></a> lanzada al dividir dos cadenas de texto no es gestionado por la cláusula <a class="reference internal" href="../reference/compound_stmts.html#except"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">except</span></code></a> y por lo tanto es relanzada luego de que se ejecuta la cláusula <code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code>.</p>
                        <p>En aplicaciones reales, la cláusula <a class="reference internal" href="../reference/compound_stmts.html#finally"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">finally</span></code></a> es útil para liberar recursos externos (como archivos o conexiones de red), sin importar si el uso del recurso fue exitoso.</p>
                        </div>
                        <div class="section" id="predefined-clean-up-actions">
                        <span id="tut-cleanup-with"></span><h2><span class="section-number">8.8. </span>Acciones predefinidas de limpieza<a class="headerlink" href="#predefined-clean-up-actions" title="Enlazar permanentemente con este título">¶</a></h2>
                        <p>Algunos objetos definen acciones de limpieza estándar para llevar a cabo cuando el objeto ya no necesario, independientemente de que las operaciones sobre el objeto hayan sido exitosas o no. Véase el siguiente ejemplo, que intenta abrir un archivo e imprimir su contenido en la pantalla.</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;myfile.txt&quot;</span><span class="p">):</span>
                            <span class="nb">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&quot;&quot;</span><span class="p">)</span>
                        </pre></div>
                        </div>
                        <p>El problema con este código es que deja el archivo abierto por un periodo de tiempo indeterminado luego de que esta parte termine de ejecutarse.  Esto no es un problema en <em>scripts</em> simples, pero puede ser un problema en aplicaciones más grandes.  La declaración <a class="reference internal" href="../reference/compound_stmts.html#with"><code class="xref std std-keyword docutils literal notranslate"><span class="pre">with</span></code></a> permite que los objetos como archivos sean usados de una forma que asegure que siempre se los libera rápido y en forma correcta.:</p>
                        <div class="highlight-python3 notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;myfile.txt&quot;</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
                            <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
                                <span class="nb">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&quot;&quot;</span><span class="p">)</span>
                        </pre></div>
                        </div>
                        <p>Una vez que la declaración se ejecuta, el fichero <em>f</em> siempre se cierra, incluso si aparece algún error durante el procesado de las líneas.  Los objetos que, como los ficheros, posean acciones predefinidas de limpieza lo indicarán en su documentación.</p>
                        </div>
                        </div>                        
                    </div>
                </div>
            </section>
            <!-- Image element - set the background image for the header in the line below-->
            <div class="py-5 bg-image-full" style="background-image: url('https://miro.medium.com/max/1838/1*HLGtY6O2vUHqIyEbWdmBgA.jpeg')">
                <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
                <div style="height: 20rem"></div>
            </div>
            <!-- Content section-->
            <!-- Footer-->
            <footer class="py-5 bg-dark">
                <div class="container"><p class="m-0 text-center text-white">Copyright &copy; RD Coding Network, 2021</p></div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src='js/scripts.js'></script>
    </body>
</html>